// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertToPDF(arg1:Array<string>,arg2:Record<string, Array<string>>):Promise<string>;

export function GetDirectoryContents(arg1:string):Promise<Array<main.FileInfo>>;

export function GetExcelSheets(arg1:string):Promise<Array<main.ExcelSheetInfo>>;

export function GetFileInfo(arg1:string):Promise<Record<string, any>>;

export function GetInitialDirectory():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;
