// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToPDF(arg1, arg2) {
  return window['go']['main']['App']['ConvertToPDF'](arg1, arg2);
}

export function GetDirectoryContents(arg1) {
  return window['go']['main']['App']['GetDirectoryContents'](arg1);
}

export function GetExcelSheets(arg1) {
  return window['go']['main']['App']['GetExcelSheets'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}
