// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeWorkingDirectory() {
  return window['go']['main']['App']['ChangeWorkingDirectory']();
}

export function ConvertToPDF(arg1, arg2) {
  return window['go']['main']['App']['ConvertToPDF'](arg1, arg2);
}

export function GetAutoUpdateEnabled() {
  return window['go']['main']['App']['GetAutoUpdateEnabled']();
}

export function GetDirectoryContents(arg1) {
  return window['go']['main']['App']['GetDirectoryContents'](arg1);
}

export function GetDirectoryTree(arg1) {
  return window['go']['main']['App']['GetDirectoryTree'](arg1);
}

export function GetExcelSheets(arg1) {
  return window['go']['main']['App']['GetExcelSheets'](arg1);
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function GetInitialDirectory() {
  return window['go']['main']['App']['GetInitialDirectory']();
}

export function GetWatchStatus() {
  return window['go']['main']['App']['GetWatchStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SetAutoUpdateEnabled(arg1) {
  return window['go']['main']['App']['SetAutoUpdateEnabled'](arg1);
}

export function SetWindowTitle(arg1) {
  return window['go']['main']['App']['SetWindowTitle'](arg1);
}

export function StartWatchingDirectory(arg1) {
  return window['go']['main']['App']['StartWatchingDirectory'](arg1);
}
