// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChangeWorkingDirectory():Promise<string>;

export function ConvertToPDF(arg1:Array<string>,arg2:Record<string, Array<string>>):Promise<string>;

export function GetAutoUpdateEnabled():Promise<boolean>;

export function GetDefaultSavePath():Promise<string>;

export function GetDirectoryContents(arg1:string):Promise<Array<main.FileInfo>>;

export function GetDirectoryTree(arg1:string):Promise<Array<main.FileInfo>>;

export function GetExcelSheets(arg1:string):Promise<Array<main.ExcelSheetInfo>>;

export function GetFileInfo(arg1:string):Promise<Record<string, any>>;

export function GetInitialDirectory():Promise<string>;

export function HasUnsavedChanges():Promise<boolean>;

export function MarkAsModified():Promise<void>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function SavePdfAs(arg1:string):Promise<void>;

export function SetAutoUpdateEnabled(arg1:boolean):Promise<void>;

export function SetWindowTitle(arg1:string):Promise<void>;

export function ShowSaveDialog():Promise<void>;

export function StartWatchingDirectory(arg1:string):Promise<void>;
